## mindspore.Tensor.min() -> Tensor
返回输入Tensor的最大值。
## mindspore.Tensor.min(dim, keepdim=False) -> tuple(Tensor)
按指定维度返回输入Tensor的最大值及其索引。
## mindspore.Tensor.min(axis=None, keepdims=False, *, initial=None, where=True, return_indices=False) -> Tensor or scalar
返回输入Tensor的最大值或最大值及索引。

1、参数比较：  
| mindspore   |              |              |
| :----:      | :----:      | :----:      |
| 重载1       | 重载2       | 重载3         |
|             | dim         | axis        |
|             | keepdim     | keepdims    |
|             |             | initial     |
|             |             | where       |
|             |             | return_indices|


| torch       |              |            |
| :----:      | :----:      | :----:      |
| 重载1       | 重载2       | 重载3         |
|             | dim         | other       |
|             | keepdim     | out         |
|             | out         |             |

| jax       |
| :----:      |
| axis        |
| out         |
| keepdims    |
| initial     |
| where       |


2、返回值比较

重载1：

In [1]:
import numpy as np
import mindspore as ms
import torch
import jax

input = np.array([[9, 3, 4, 5],
                  [5, 2, 7, 4],
                  [8, 1, 3, 6]])

y1 = ms.tensor(input)
y1_output = y1.min()
y2 = torch.tensor(input)
y2_output = y2.min()
y3_output = input.min()
print ('mindspore output:\n',y1_output)
print('\n')
print ('torch output:\n',y2_output)
print('\n')
print ('jax output:\n',y3_output)

mindspore output:
 1


torch output:
 tensor(1)


jax output:
 1


* ms与jax不返回类型。

重载2：

In [2]:
y1 = ms.tensor(input)
y1_output = y1.min(dim=1, keepdim=True)
y2 = torch.tensor(input)
y2_output = y2.min(dim=1, keepdim=True)
y3 = input
y3_output = y3.min(axis=1, keepdims=True)
print ('mindspore output:\n',y1_output)
print('\n')
print ('torch output:\n',y2_output)
print('\n')
print ('jax output:\n',y3_output)

mindspore output:
 (Tensor(shape=[3, 1], dtype=Int64, value=
[[3],
 [2],
 [1]]), Tensor(shape=[3, 1], dtype=Int64, value=
[[1],
 [1],
 [1]]))


torch output:
 torch.return_types.min(
values=tensor([[3],
        [2],
        [1]]),
indices=tensor([[1],
        [1],
        [1]]))


jax output:
 [[3]
 [2]
 [1]]


* jax不返回最大值的索引。

重载3：ms与jax

In [3]:
where=np.array([[0, 0, 0, 0],
                [0, 1, 0, 1],
                [1, 1, 1, 0]], dtype=bool)

y1 = ms.tensor(input)
y1_output = y1.min(axis=1, keepdims=True, initial=0, where=ms.tensor(where), return_indices=True)
y3 = input
y3_output = y3.min(axis=1, keepdims=True, initial=0, where=ms.tensor(where))
print ('mindspore output:\n',y1_output)
print('\n')
print ('jax output:\n',y3_output)

mindspore output:
 (Tensor(shape=[3, 1], dtype=Int64, value=
[[0],
 [0],
 [0]]), Tensor(shape=[3, 1], dtype=Int64, value=
[[0],
 [0],
 [0]]))


jax output:
 [[0]
 [0]
 [0]]


* jax不返回最大值的索引。

In [4]:
other=np.array([[10, 0, 0, 0],
                [0, 1, 0, 1],
                [1, 1, 5, 0]])
y2 = torch.tensor(input)
y2_output = y2.min(torch.tensor(other))
print ('torch output:\n',y2_output)

torch output:
 tensor([[9, 0, 0, 0],
        [0, 1, 0, 1],
        [1, 1, 3, 0]])


3、报错信息比较

In [5]:
y1_output = y1.min(dim=(1,2), keepdim=True)

TypeError: Failed calling min with "min(dim=Tuple<int, int>, keepdim=bool)".
The valid calling should be:
"Tensor.min()"
"Tensor.min(dim=<int>, keepdim=<bool>)"
"Tensor.min(axis=<int,Tuple,None,List>, keepdims=<bool>, *, initial=<number,None>, where=<bool,Tensor>, return_indices=<bool>)"


----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/op_function/converter.h:112 Parse


In [6]:
y2_output = y2.min(dim=(1,2), keepdim=True)

TypeError: min() received an invalid combination of arguments - got (keepdim=bool, dim=tuple, ), but expected one of:
 * ()
 * (Tensor other)
 * (int dim, bool keepdim)
      didn't match because some of the arguments have invalid types: (!dim=tuple of (int, int)!, keepdim=bool, )
 * (name dim, bool keepdim)
      didn't match because some of the arguments have invalid types: (!dim=tuple of (int, int)!, keepdim=bool, )


In [7]:
y3_output = y3.min(axis=(1,1), keepdims=True)

ValueError: duplicate value in 'axis'

当输入类型不正确时，ms报错信息与torch对齐。