## mindspore.ops.eye(n, m=None, dtype=None) -〉 Tensor
创建一个主对角线上元素为1，其余元素为0的Tensor。
- 输入：
    * n：int，行数。
    * m：int，列数。
    * dtype：mindspore.dtype。
- 返回：mindspore的tensor。

1、参数比较：

| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| n           | n           | n           |
| m           | m           | m           |
| dtype       | out         | k           |
|             | dtype       | dtype       |
|             | layout      | device      |
|             | device      |             |
|             | requires_grad|            |

* torch和jax都提供了device参数，用于设置返回值提交到哪个设备上。
* torch额外提供了out出参，layout用于设置内存存储结构，以及requires_grad设置自动求导是否记录操作。
* jax额外提供了参数k，用于设置对角线的偏移量。

2、返回值比较

In [12]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

y1 = ms.ops.eye(3, 5, dtype = ms.float32)
y2 = torch.eye(3, 5, dtype = torch.float32)
y3 = jnp.eye(3, 5, dtype = np.float32)
y4 = jnp.eye(3, 5, k = 1, dtype = np.float32)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)
print('\n')
print ('jax output with k:\n',y4)

mindspore output:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


torch output:
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])


jax output:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


jax output with k:
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


* ms与jax不返回类型。

3、报错信息比较

In [13]:
y1 = ms.ops.eye([3], [5])

TypeError: Failed calling Eye with "Eye()(n=List<int>, m=List<int>, dtype=mindspore.dtype)".
The valid calling should be: 
"Eye()(n=<int>, m=<int>, dtype=<mindspore.dtype>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [14]:
y2 = torch.eye([3], [5])

TypeError: eye() received an invalid combination of arguments - got (list, list), but expected one of:
 * (int n, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (int n, int m, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


In [15]:
y3 = jnp.eye([3], [5])

TypeError: Shapes must be 1D sequences of concrete values of integer type, got ([3],). 'N' argument of jnp.eye().

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。