## mindspore.ops.expand_dims(input_x, axis) -〉 Tensor
对输入在给定的轴上添加额外维度。
- 输入：
    * input_x：mindspore的tensor。
    * axis：int。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   |jax         |
| :----:      |:----:      |
| input_x     |a           |
| axis        |axis        |

2、返回值比较

In [1]:
import numpy as np
import mindspore as ms
import jax.numpy as jnp

input = np.array([1, 2, 3])

y1 = ms.ops.expand_dims(ms.tensor(input), 0)
y2 = jnp.expand_dims(input, 0)
print ('mindspore output:\n',y1, y1.shape)
print('\n')
print ('jax output:\n',y1, y2.shape)

mindspore output:
 [[1 2 3]] (1, 3)


jax output:
 [[1 2 3]] (1, 3)


In [2]:
y1 = ms.ops.expand_dims(ms.tensor(input), 1)
y2 = jnp.expand_dims(input, 1)
print ('mindspore output:\n',y1, y1.shape)
print('\n')
print ('jax output:\n',y1, y2.shape)

mindspore output:
 [[1]
 [2]
 [3]] (3, 1)


jax output:
 [[1]
 [2]
 [3]] (3, 1)


In [12]:
y2 = jnp.expand_dims(input, (0, 1, 3))
print ('jax output:\n',y1, y2.shape)

jax output:
 [[1]
 [2]
 [3]] (1, 1, 3, 1)


* jax的axis参数可以接受传入tuple, ms不接受，仅能传入int。

3、报错信息比较

In [17]:
y1 = ms.ops.expand_dims(input, 0)

TypeError: Failed calling ExpandDims with "ExpandDims()(input_x=<class 'numpy.ndarray'>, axis=int)".
The valid calling should be: 
"ExpandDims()(input_x=<Tensor>, axis=<Tensor, int>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [18]:
input = [2, 4, 3, 1]
y3 = jnp.expand_dims(input, 0)

TypeError: expand_dims requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，建议ms优化报错信息。