## mindspore.ops.outer(input, vec2) -〉 Tensor
计算两个输入的外积。
- 输入：input和vec2必须为mindspore的一维tensor。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | a           |
| vec2        | vec2        | b           |
|             | out         | out(unused) |

* torch额外提供了out出参方式

2、返回值比较

当input和vec2为1维时：

In [4]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([3, -1, 4])
vec2 = np.array([2, 3, -5])

y1 = ms.ops.outer(ms.tensor(input), ms.tensor(vec2))
y2 = torch.outer(torch.tensor(input), torch.tensor(vec2))
y3 = jnp.outer(input, vec2)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)


mindspore output:
 [[  6   9 -15]
 [ -2  -3   5]
 [  8  12 -20]]


torch output:
 tensor([[  6,   9, -15],
        [ -2,  -3,   5],
        [  8,  12, -20]])


jax output:
 [[  6   9 -15]
 [ -2  -3   5]
 [  8  12 -20]]


当input为2维时：

In [8]:
input = np.array([[3, -1, 4],
                  [8, 5, -2]])
vec2 = np.array([2, 3, -5])

y1 = ms.ops.outer(ms.tensor(input), ms.tensor(vec2))
#y2 = torch.outer(torch.tensor(input), torch.tensor(vec2))
y3 = jnp.outer(input, vec2)
print ('mindspore output:\n',y1)
print('\n')
#print ('torch output:\n',y2)
#print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[  6   9 -15]
 [ -2  -3   5]
 [  8  12 -20]
 [ 16  24 -40]
 [ 10  15 -25]
 [ -4  -6  10]]


jax output:
 [[  6   9 -15]
 [ -2  -3   5]
 [  8  12 -20]
 [ 16  24 -40]
 [ 10  15 -25]
 [ -4  -6  10]]


* ms和jax会对多维数组展平后再做内积。torch不接受多维数组，会直接报错。
* ms与jax不返回类型。

3、报错信息比较

In [9]:
y1 = ms.ops.outer(input, other)

TypeError: the input input must be Tensor!

In [10]:
y2 = torch.outer(input, other)

TypeError: outer(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [11]:
input = [2, 4, 3, 1]
y3 = jnp.outer(input, other)

TypeError: outer requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。