## mindspore.ops.dsplit(input, indices_or_sections) -〉 tuple[Tensor]
沿着第三轴将输入Tensor分割成多个子Tensor。等同于axis = 2时的 ops.tensor_split 。
- 输入：
    * input (Tensor)
    * indices_or_sections (Union[int, tuple(int), list(int)])
- 返回：mindspore的tensor。

## 1、参数比较：
| mindspore   | torch       |
| :----:      | :----:      |
| input       | input       |
| indices_or_sections  | indices_or_sections        |

## 2、返回值比较  
当indices_or_sections 为 int时：

In [52]:
import numpy as np
import torch
import mindspore as ms
from mindspore import Tensor, ops

input = np.arange(16.0).reshape(2, 2, 4)
print("input:\n", input)
print("\n")
output1 = torch.dsplit(torch.tensor(input), 2)
print("torch output:\n", output1)
print("\n")
output2 = ms.ops.dsplit(ms.tensor(input), 2)
print("ms output:\n", output2)

input:
 [[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]]

 [[ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]]


torch output:
 (tensor([[[ 0.,  1.],
         [ 4.,  5.]],

        [[ 8.,  9.],
         [12., 13.]]], dtype=torch.float64), tensor([[[ 2.,  3.],
         [ 6.,  7.]],

        [[10., 11.],
         [14., 15.]]], dtype=torch.float64))


ms output:
 (Tensor(shape=[2, 2, 2], dtype=Float64, value=
[[[ 0.00000000e+00,  1.00000000e+00],
  [ 4.00000000e+00,  5.00000000e+00]],
 [[ 8.00000000e+00,  9.00000000e+00],
  [ 1.20000000e+01,  1.30000000e+01]]]), Tensor(shape=[2, 2, 2], dtype=Float64, value=
[[[ 2.00000000e+00,  3.00000000e+00],
  [ 6.00000000e+00,  7.00000000e+00]],
 [[ 1.00000000e+01,  1.10000000e+01],
  [ 1.40000000e+01,  1.50000000e+01]]]))


当indices_or_sections 为list时：

In [26]:
output1 = torch.dsplit(torch.tensor(input), [3, 6])
print("torch output1:\n", output1)
print("\n")
output2 = ms.ops.dsplit(ms.tensor(input), [3, 6])
print("ms output2:\n", output1)

torch output1:
 (tensor([[[ 0.,  1.,  2.],
         [ 4.,  5.,  6.]],

        [[ 8.,  9., 10.],
         [12., 13., 14.]]], dtype=torch.float64), tensor([[[ 3.],
         [ 7.]],

        [[11.],
         [15.]]], dtype=torch.float64), tensor([], size=(2, 2, 0), dtype=torch.float64))


ms output2:
 (tensor([[[ 0.,  1.,  2.],
         [ 4.,  5.,  6.]],

        [[ 8.,  9., 10.],
         [12., 13., 14.]]], dtype=torch.float64), tensor([[[ 3.],
         [ 7.]],

        [[11.],
         [15.]]], dtype=torch.float64), tensor([], size=(2, 2, 0), dtype=torch.float64))


### 与tensor_split接口比较：

In [54]:
output1 = torch.tensor_split(torch.tensor(input), 2, 2)
print("torch output1:\n", output1)
output2 = torch.tensor_split(torch.tensor(input), [3, 6], 2)
print("torch output2:\n", output2)

torch output1:
 (tensor([[[ 0.,  1.],
         [ 4.,  5.]],

        [[ 8.,  9.],
         [12., 13.]]], dtype=torch.float64), tensor([[[ 2.,  3.],
         [ 6.,  7.]],

        [[10., 11.],
         [14., 15.]]], dtype=torch.float64))
torch output2:
 (tensor([[[ 0.,  1.,  2.],
         [ 4.,  5.,  6.]],

        [[ 8.,  9., 10.],
         [12., 13., 14.]]], dtype=torch.float64), tensor([[[ 3.],
         [ 7.]],

        [[11.],
         [15.]]], dtype=torch.float64), tensor([], size=(2, 2, 0), dtype=torch.float64))


In [33]:
output1 = ms.ops.tensor_split(ms.tensor(input), 2, 2)
print("ms output1:\n", output1)
output2 = ms.ops.tensor_split(ms.tensor(input), [3, 6], 2)
print("ms output2:\n", output2)

ms output1:
 (Tensor(shape=[2, 2, 2], dtype=Float64, value=
[[[ 0.00000000e+00,  1.00000000e+00],
  [ 4.00000000e+00,  5.00000000e+00]],
 [[ 8.00000000e+00,  9.00000000e+00],
  [ 1.20000000e+01,  1.30000000e+01]]]), Tensor(shape=[2, 2, 2], dtype=Float64, value=
[[[ 2.00000000e+00,  3.00000000e+00],
  [ 6.00000000e+00,  7.00000000e+00]],
 [[ 1.00000000e+01,  1.10000000e+01],
  [ 1.40000000e+01,  1.50000000e+01]]]))
ms output2:
 (Tensor(shape=[2, 2, 3], dtype=Float64, value=
[[[ 0.00000000e+00,  1.00000000e+00,  2.00000000e+00],
  [ 4.00000000e+00,  5.00000000e+00,  6.00000000e+00]],
 [[ 8.00000000e+00,  9.00000000e+00,  1.00000000e+01],
  [ 1.20000000e+01,  1.30000000e+01,  1.40000000e+01]]]), Tensor(shape=[2, 2, 1], dtype=Float64, value=
[[[ 3.00000000e+00],
  [ 7.00000000e+00]],
 [[ 1.10000000e+01],
  [ 1.50000000e+01]]]), Tensor(shape=[2, 2, 0], dtype=Float64, value=
))


In [41]:
a = torch.arange(10).reshape(5, 2)
torch.split(a, 3)

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[6, 7],
         [8, 9]]))

当axis=2时，ms与torch的dsplit与tensor_split接口返回值一致。
但ms的两个接口输出格式有区别。

### 与torch.split的比较：  
第二个参数含义不同：
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
table{border-top:1px solid #333;border-left:1px solid #333;border-spacing:0;background-color:#fff;width:100%}
table td{border-bottom:1px solid #333;border-right:1px solid #333;font-size:13px;padding:5px}
.et2{text-align:center ;}
.font0{color:rgb(0, 0, 0);}
</style>
</head>
<body>
    <table style="width:358.02pt"> 
 <colgroup>
  <col width="48" style="width:48.00pt;"> 
  <col width="170" style="width:170.00pt;"> 
  <col width="140" style="width:140.80pt;"> 
 </colgroup>
 <tbody>
  <tr height="16"> 
   <td class="et2"></td> 
   <td class="et2">torch.dsplit: indices_or_sections</td> 
   <td class="et2">torch.split: split_size_or_sections</td> 
  </tr> 
  <tr height="16"> 
   <td class="et2">int</td> 
   <td class="et2">切分的份数</td> 
   <td class="et2">切分每份的大小</td> 
  </tr> 
  <tr height="16"> 
   <td class="et2">list</td> 
   <td class="et2">在索引处进行切分</td> 
   <td class="et2">切分每份的大小</td> 
  </tr> 
 </tbody>
</table>
</body>
</html>

所以为了得到同样的输出，入参需要改变，如下：

In [55]:
output1 = torch.split(torch.tensor(input), 2, 2)
print("torch output1:\n", output1)
output2 = torch.split(torch.tensor(input), [3, 1], 2)
print("torch output2:\n", output2)

torch output1:
 (tensor([[[ 0.,  1.],
         [ 4.,  5.]],

        [[ 8.,  9.],
         [12., 13.]]], dtype=torch.float64), tensor([[[ 2.,  3.],
         [ 6.,  7.]],

        [[10., 11.],
         [14., 15.]]], dtype=torch.float64))
torch output2:
 (tensor([[[ 0.,  1.,  2.],
         [ 4.,  5.,  6.]],

        [[ 8.,  9., 10.],
         [12., 13., 14.]]], dtype=torch.float64), tensor([[[ 3.],
         [ 7.]],

        [[11.],
         [15.]]], dtype=torch.float64))
