## mindspore.ops.stack(tensors, axis=0) -〉 Tensor
在指定轴上对输入进行堆叠。
- 输入：
    * tensors：由多个mindspore的tensor组成的tuple或list。
    * axis：int。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| tensors     | tensors     | array       |
| axis        | dim         | axis        |
|             | out         | out(unused) | 
|             |             | dtype       |

* torch额外提供了out出参方式。
* jax可以通过dtype设置返回的数据类型。

2、返回值比较

In [22]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

y1 = ms.ops.stack((ms.tensor(x), ms.tensor(y)))
y2 = torch.stack((torch.tensor(x), torch.tensor(y)))
y3 = jnp.stack([x, y])
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[1 2 3]
 [4 5 6]]


torch output:
 tensor([[1, 2, 3],
        [4, 5, 6]])


jax output:
 [[1 2 3]
 [4 5 6]]


In [23]:
y1 = ms.ops.stack((ms.tensor(x), ms.tensor(y)), 1)
y2 = torch.stack((torch.tensor(x), torch.tensor(y)), 1)
y3 = jnp.stack([x, y], 1)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[1 4]
 [2 5]
 [3 6]]


torch output:
 tensor([[1, 4],
        [2, 5],
        [3, 6]])


jax output:
 [[1 4]
 [2 5]
 [3 6]]


* ms与jax不返回类型。

3、报错信息比较

In [24]:
y1 = ms.ops.stack(input)

TypeError: Infer type failed.

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ops/infer/stack.cc:122 StackInferType


In [27]:
y2 = torch.stack(input)

TypeError: stack(): argument 'tensors' (position 1) must be tuple of Tensors, not method

In [29]:
y3 = jnp.stack(torch.tensor(x))

TypeError: stack requires ndarray or scalar arguments, got <class 'torch.Tensor'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。