## mindspore.ops.swapaxes(input, axis0, axis1) -〉 Tensor
交换输入的两个维度。
- 输入：
    * input：mindspore的tensor。
    * axis0：int。
    * axis1：int。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | a           |
| axis0       | axis0       | axis1       |
| axis1       | axis1       | axis2       |


2、返回值比较

In [6]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([[[0, 1, 2],
                   [3, 4, 5]],

                  [[6, 7, 8],
                   [9, 10, 11]]])

y1 = ms.ops.swapaxes(ms.tensor(input), 0, 2)
y2 = torch.swapaxes(torch.tensor(input), 0, 2)
y3 = jnp.swapaxes(input, 0, 2)
print('input shape:', input.shape)
print ('mindspore output:\n',y1)
print('output shape:', y1.shape)
print('\n')
print ('torch output:\n',y2)
print('output shape:', y2.shape)
print('\n')
print ('jax output:\n',y3)
print('output shape:', y2.shape)

input shape: (2, 2, 3)
mindspore output:
 [[[ 0  6]
  [ 3  9]]

 [[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]]
output shape: (3, 2, 2)


torch output:
 tensor([[[ 0,  6],
         [ 3,  9]],

        [[ 1,  7],
         [ 4, 10]],

        [[ 2,  8],
         [ 5, 11]]])
output shape: torch.Size([3, 2, 2])


jax output:
 [[[ 0  6]
  [ 3  9]]

 [[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]]
output shape: torch.Size([3, 2, 2])


* ms与jax不返回类型。

3、报错信息比较

In [7]:
y1 = ms.ops.swapaxes(input, 0, 2)

TypeError: For ops.swapaxes, parameter `input` must be Tensor, but got <class 'numpy.ndarray'>

In [8]:
y2 = torch.swapaxes(input, 0, 2)

TypeError: swapaxes(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [9]:
input = [2, 4, 3, 1]
y3 = jnp.swapaxes(input, 0, 2)

TypeError: swapaxes requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。