## mindspore.ops.zeros_like(input, *, dtype=None) -〉 Tensor
返回值为0的Tensor，shape与输入相同。
- 输入：
    * input: mindspore的tensor
    * dtype: mindspore.dtype
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | a           |
| dtype       | dtype       | shape       |
|             | layout      | dtype       |
|             | device      | device      |
|             | requires_grad   |        |
|             | memory_format   |        |


* torch额外提供了layout用于设置内存存储结构，requires_grad设置自动求导是否记录操作以及memory_format内存存储方式。
* jax额外提供了shape参数用于覆盖input的shape。
* torch和jax都提供了device参数，用于设置返回值提交到哪个设备上。

2、返回值比较

In [2]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([0., -3., 7, -7])

y1 = ms.ops.zeros_like(ms.tensor(input))
y2 = torch.zeros_like(torch.tensor(input))
y3 = jnp.zeros_like(input)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [0. 0. 0. 0.]


torch output:
 tensor([0., 0., 0., 0.], dtype=torch.float64)


jax output:
 [0. 0. 0. 0.]


通过shape参数覆盖input的shape:

In [3]:
y3 = jnp.zeros_like(input, shape=(2,3))
print ('jax output:\n',y3)

jax output:
 [[0. 0. 0.]
 [0. 0. 0.]]


* ms与jax不返回类型。

3、报错信息比较：

In [4]:
y1 = ms.ops.zeros_like(1.5)

AttributeError: 'float' object has no attribute 'dtype'

In [5]:
y2 = torch.zeros_like(1.5)

TypeError: zeros_like(): argument 'input' (position 1) must be Tensor, not float

In [6]:
input = [2, 4, 3, 1]
y3 = jnp.zeros_like(input)

TypeError: zeros_like requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。