## mindspore.ops.repeat_interleave(input, repeats, axis=None) -〉 Tensor
按指定轴重复Tensor的元素。
- 输入：
    * input：mindspore的tensor。
    * repeats：int, tuple, list, mindspore的tensor。
    * axis：int。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | a           |
| repeats     | repeats     | repeats     |
| axis        | dim         | axis        |
|             | output_size | total_repeat_length |

* torch与jax提供了output_size和total_repeat_length参数，用于设定重复次数。

2、返回值比较

In [5]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([[1, 2],
                  [3, 4]])

y1 = ms.ops.repeat_interleave(ms.tensor(input), 2, 1)
y2 = torch.repeat_interleave(torch.tensor(input), 2, 1)
y3 = jnp.repeat(input, 2, 1)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[1 1 2 2]
 [3 3 4 4]]


torch output:
 tensor([[1, 1, 2, 2],
        [3, 3, 4, 4]])


jax output:
 [[1 1 2 2]
 [3 3 4 4]]


In [19]:
y1 = ms.ops.repeat_interleave(input, 2, 1)
print ('mindspore output:\n',y1)

y1 = ms.ops.repeat_interleave(torch.tensor(input), 2, 1)
print ('mindspore output:\n',y1)

mindspore output:
 [[1 1 2 2]
 [3 3 4 4]]
mindspore output:
 tensor([[1, 2],
        [3, 4],
        [1, 2],
        [3, 4]])


* 实测发现ms可接受array/torch.tensor输入，文档未体现, 且与其他接口不一致。
* ms与jax不返回类型。

设置重复次数：

In [12]:
# y2 = torch.repeat_interleave(torch.tensor(input), 2, 1, output_size=6)
y3 = jnp.repeat(input, 2, 1, total_repeat_length=6)
# print ('torch output:\n',y2)
print ('jax output:\n',y3)

jax output:
 [[1 1 2 2 2 2]
 [3 3 4 4 4 4]]


除4外torch不能设置其他值，jax可随意设置。

3、报错信息比较

In [20]:
input = [2, 4, 3, 1]
y1 = ms.ops.repeat_interleave(input, 2, 1)
print ('mindspore output:\n',y1)

AttributeError: 'list' object has no attribute 'repeat'

In [21]:
y2 = torch.repeat_interleave(input, 2, 1)

TypeError: repeat_interleave() received an invalid combination of arguments - got (list, int, int), but expected one of:
 * (Tensor input, Tensor repeats, int dim, *, int output_size)
 * (Tensor repeats, *, int output_size)
      didn't match because some of the arguments have invalid types: (!list of [int, int, int, int]!, !int!, int)
 * (Tensor input, int repeats, int dim, *, int output_size)


In [25]:
input = [2, 4, 3, 1]
y3 = jnp.repeat(input, 2, 1)

TypeError: repeat requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。