## mindspore.ops.remainder(input, other) -〉 Tensor
计算第一个输入元素除以第二个输入元素的余数。
- 输入：input和other必须为numbers.Number、bool或mindspore的tensor（数据类型为Number）。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | x1          |
| other       | other       | x2          |
|             | out         |             |

* torch额外提供了out出参方式

2、返回值比较

In [2]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([[3, -1, 4],
                  [8, 5, -2]])
other = np.array([2, 3, -5])

y1 = ms.ops.remainder(ms.tensor(input), ms.tensor(other))
y2 = torch.remainder(torch.tensor(input), torch.tensor(other))
y3 = jnp.remainder(input, other)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[ 1  2 -1]
 [ 0  2 -2]]


torch output:
 tensor([[ 1,  2, -1],
        [ 0,  2, -2]])


jax output:
 [[ 1  2 -1]
 [ 0  2 -2]]


* ms与jax不返回类型。

3、报错信息比较

In [5]:
y1 = ms.ops.remainder(input, other)

TypeError: Failed calling FloorDiv with "FloorDiv()(input=List<int, int, int, int>, other=<class 'numpy.ndarray'>)".
The valid calling should be: 
"FloorDiv()(input=<Number, Tensor>, other=<Number, Tensor>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [4]:
y2 = torch.remainder(input, other)

TypeError: remainder() received an invalid combination of arguments - got (list, numpy.ndarray), but expected one of:
 * (Tensor input, Tensor other, *, Tensor out)
 * (Number self, Tensor other)
      didn't match because some of the arguments have invalid types: (!list of [int, int, int, int]!, !numpy.ndarray!)
 * (Tensor input, Number other, *, Tensor out)


In [3]:
input = [2, 4, 3, 1]
y3 = jnp.remainder(input, other)

TypeError: remainder requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。