## mindspore.ops.triu(input, diagonal=0) -〉 Tensor
返回输入的对角线和上面的元素，并将其他元素设置为0。
- 输入：
    * input：mindspore的tensor。
    * diagonal：int。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | m           |
| diagonal    | diagonal    | k           |
|             | out         |             |

* torch额外提供了out出参。

2、返回值比较

二维输入下diagonal默认值比较：

In [2]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

y1 = ms.ops.triu(ms.tensor(input))
y2 = torch.triu(torch.tensor(input))
y3 = jnp.triu(input)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[ 1  2  3  4]
 [ 0  6  7  8]
 [ 0  0 11 12]]


torch output:
 tensor([[ 1,  2,  3,  4],
        [ 0,  6,  7,  8],
        [ 0,  0, 11, 12]])


jax output:
 [[ 1  2  3  4]
 [ 0  6  7  8]
 [ 0  0 11 12]]


In [3]:
y1 = ms.ops.triu(ms.tensor(input), 1)
y2 = torch.triu(torch.tensor(input), 1)
y3 = jnp.triu(input, 1)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[ 0  2  3  4]
 [ 0  0  7  8]
 [ 0  0  0 12]]


torch output:
 tensor([[ 0,  2,  3,  4],
        [ 0,  0,  7,  8],
        [ 0,  0,  0, 12]])


jax output:
 [[ 0  2  3  4]
 [ 0  0  7  8]
 [ 0  0  0 12]]


三维输入：

In [4]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([[[1, 2],
                  [3, 4]],
                 [[5, 6],
                  [7, 8]]])

y1 = ms.ops.triu(ms.tensor(input))
y2 = torch.triu(torch.tensor(input))
y3 = jnp.triu(input)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[[1 2]
  [0 4]]

 [[5 6]
  [0 8]]]


torch output:
 tensor([[[1, 2],
         [0, 4]],

        [[5, 6],
         [0, 8]]])


jax output:
 [[[1 2]
  [0 4]]

 [[5 6]
  [0 8]]]


* ms与jax不返回类型。

3、报错信息比较

In [5]:
y1 = ms.ops.triu(input)

TypeError: Failed calling Triu with "Triu(diagonal=int)(input=<class 'numpy.ndarray'>)".
The valid calling should be: 
"Triu(diagonal=<Tensor, int>)(input=<Tensor>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [6]:
y2 = torch.triu(input)

TypeError: triu(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [7]:
input = [2, 4, 3, 1]
y3 = jnp.triu(input)

TypeError: triu requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。