## mindspore.ops.pad(input_x, padding, mode='constant', value=None) -〉Tensor
对输入进行填充。
- 输入：
    * input_x: mindspore的tensor。
    * padding: tuple[int], list[int], Tensor。
    * mode: str枚举值包含：'constant' 、 'reflect' 、 'replicate' 或者 'circular'。
    * value: int, float, None。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input_x     | input       | array       |
| padding     | pad         | pad_width   |
| mode        | mode        | mode        |
| value       | value       | constant_values  |
|             |             | stat_length    |
|             |             | end_values     |
|             |             | reflect_type |

* 对于mode参数，ms与torch的枚举类型一致，与jax提供的枚举值有差异。
* jax额外提供了stat_length、end_values和reflect_type参数，都用于特定mode情况下计算。

2、返回值比较

一维数组：

In [5]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([10, 20, 30, 40])

y1 = ms.ops.pad(ms.tensor(input), (2, 4), value=99)
y2 = torch.nn.functional.pad(torch.tensor(input), (2, 4), value=99)
y3 = jnp.pad(input, (2, 4), constant_values=99)
print ('mindspore output:',y1)
print ('torch output:',y2)
print ('jax outputn',y3)

mindspore output: [99 99 10 20 30 40 99 99 99 99]
torch output: tensor([99, 99, 10, 20, 30, 40, 99, 99, 99, 99])
jax outputn [99 99 10 20 30 40 99 99 99 99]


二维数组：

In [37]:
input = np.array([[[[10, 20, 30, 40],
                    [50, 60, 70, 80]],
                   [[10, 20, 30, 40],
                    [50, 60, 70, 80]]]])

y1 = ms.ops.pad(ms.tensor(input), [0, 1, 0, 1], mode='reflect')
y2 = torch.nn.functional.pad(torch.tensor(input), [0, 1, 0, 1], mode='reflect')
y3 = jnp.pad(input, [[0,0], [0, 0], [0,1], [0, 1]], mode='reflect')
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[[[10 20 30 40 30]
   [50 60 70 80 70]
   [10 20 30 40 30]]

  [[10 20 30 40 30]
   [50 60 70 80 70]
   [10 20 30 40 30]]]]


torch output:
 tensor([[[[10, 20, 30, 40, 30],
          [50, 60, 70, 80, 70],
          [10, 20, 30, 40, 30]],

         [[10, 20, 30, 40, 30],
          [50, 60, 70, 80, 70],
          [10, 20, 30, 40, 30]]]])


jax output:
 [[[[10 20 30 40 30]
   [50 60 70 80 70]
   [10 20 30 40 30]]

  [[10 20 30 40 30]
   [50 60 70 80 70]
   [10 20 30 40 30]]]]


* ms与torch的第二、三个参数及使用方式一致，与jax不同。
* m与jax都不返回类型

3、报错信息比较

In [38]:
y1 = ms.ops.pad(input, [0, 1, 0, 1])

TypeError: For 'pad', the type of 'input_x' must be Tensor, but got <class 'numpy.ndarray'>.

In [39]:
y2 = torch.nn.functional.pad(input, [0, 1, 0, 1])

TypeError: pad(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [40]:
input = [2, 4, 3, 1]
y3 = jnp.pad(input, [[0,0], [0, 0], [0,1], [0, 1]])

TypeError: pad requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。