## mindspore.ops.var(input, axis=None, ddof=0, keepdims=False) -〉 Tensor
按指定维度返回输入Tensor上的方差。
- 输入：
    * input：mindspore的tensor(数据类型为Number)。
    * axis：int, tuple(int)。
    * ddof：int, bool。
    * keepdims：bool。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | a           |
| axis        | dim         | axis        |
| ddof        | correction  | dtype       |
| keepdims    | keepdim     | out (unused)|
|             | out         | ddof        |
|             |             | keepdims    |
|             |             | where       |
|             |             | correction  |

* jax额外提供了dtype、where和correction参数，分别用于设置返回值的数据类型、数组位置上的元素是否参与计算方差。
* torch额外提供了out出参。

2、返回值比较

In [5]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([[1., 3, 4, 2],
                  [5, 2, 6, 3],
                  [8, 4, 2, 9]])

y1 = ms.ops.var(ms.tensor(input))
y2 = torch.var(torch.tensor(input))
y3 = jnp.var(input)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 5.743055083152285


torch output:
 tensor(6.2652, dtype=torch.float64)


jax output:
 5.7430553


In [8]:
y1 = ms.ops.var(ms.tensor(input), 1, keepdims=True, ddof=1)
y2 = torch.var(torch.tensor(input), 1, correction=1, keepdim=True)
y3 = jnp.var(input, 1, keepdims=True, ddof=1)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[ 1.66666656]
 [ 3.33333344]
 [10.91666742]]


torch output:
 tensor([[ 1.6667],
        [ 3.3333],
        [10.9167]], dtype=torch.float64)


jax output:
 [[ 1.6666666]
 [ 3.3333333]
 [10.916667 ]]


* ms与jax不返回类型。

3、报错信息比较

In [9]:
y1 = ms.ops.var(input)

TypeError: For var, input must be a Tensor, but got <class 'numpy.ndarray'>.

In [10]:
y2 = torch.var(input)

TypeError: var() received an invalid combination of arguments - got (numpy.ndarray), but expected one of:
 * (Tensor input, tuple of ints dim, bool unbiased, bool keepdim, *, Tensor out)
 * (Tensor input, tuple of ints dim, *, Number correction, bool keepdim, Tensor out)
 * (Tensor input, bool unbiased)
 * (Tensor input, tuple of names dim, bool unbiased, bool keepdim, *, Tensor out)
 * (Tensor input, tuple of names dim, *, Number correction, bool keepdim, Tensor out)


In [12]:
input = [2, 4, 3, 1]
y3 = jnp.var(input)

TypeError: var requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。