## mindspore.ops.reshape(input, shape) -〉 Tensor
根据shape对输入进行重新排列。
- 输入：
    * input：mindspore的tensor。
    * shape：tuple[int], list[int], Tensor[int]。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | a           |
| shape       | shape       | shape       |
|             |             | order       |
|             |             | copy (unused)  |
|             |             | newshape (deprecated)|

* jax提供了order参数, 用于设置按行排序还是按列排序。

2、返回值比较

In [7]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([[1, 2, 3],
                  [4, 5, 6]])

y1 = ms.ops.reshape(ms.tensor(input), (6, ))
y2 = torch.reshape(torch.tensor(input), (6, ))
y3 = jnp.reshape(input, 6)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [1 2 3 4 5 6]


torch output:
 tensor([1, 2, 3, 4, 5, 6])


jax output:
 [1 2 3 4 5 6]


jax可接受shape为int, ms与torch不接受。

使用-1自动计算出应有的shape，如：

In [9]:
y1 = ms.ops.reshape(ms.tensor(input), (-1, 2))
y2 = torch.reshape(torch.tensor(input), (-1, 2))
y3 = jnp.reshape(input, (-1, 2))
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[1 2]
 [3 4]
 [5 6]]


torch output:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])


jax output:
 [[1 2]
 [3 4]
 [5 6]]


jax.numpy.reshape的order参数使用：

In [13]:
y1 = jnp.reshape(input, (-1, 2), order='F')
y2 = jnp.reshape(input, (-1, 2), order='C')
print ('order F output:\n',y1)
print('\n')
print ('order C output:\n',y2)

order F output:
 [[1 5]
 [4 3]
 [2 6]]


order C output:
 [[1 2]
 [3 4]
 [5 6]]


3、报错信息比较

In [15]:
y1 = ms.ops.reshape(input, (-1, 2))

TypeError: Failed calling Reshape with "Reshape()(input=<class 'numpy.ndarray'>, shape=Tuple<int, int>)".
The valid calling should be: 
"Reshape()(input=<Tensor>, shape=<Tensor, list of int, tuple of int>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [17]:
y2 = torch.reshape(input, (-1, 2))

TypeError: reshape(): argument 'input' (position 1) must be Tensor, not list

In [16]:
input = [2, 4, 3, 1]
y3 = jnp.reshape(input, (-1, 2))

TypeError: reshape requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。