## mindspore.ops.round(input, *, decimals=0) -〉 Tensor
返回输入四舍五入后的整数值。
- 输入：
    * input：mindspore的tensor。
    * decimals：int, 要保留的小数位数。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | a           |
| decimals    | decimals    | decimals    |
|             | out         | out(unused) |

* torch额外提供了out出参方式。

2、返回值比较

In [11]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([1.532, 3.267, 6.149])

y1 = ms.ops.round(ms.tensor(input), decimals=2)
print ('mindspore output:\n',y1)

mindspore output:
 

RuntimeError: For Round only support decimals equal 0, but got decimals equal 2

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ops/kernel/cpu/round_cpu_kernel.cc:50 LaunchKernel


In [13]:
y2 = torch.round(torch.tensor(input), decimals=2)
y3 = jnp.round(input, 2)
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

torch output:
 tensor([1.5300, 3.2700, 6.1500], dtype=torch.float64)


jax output:
 [1.53 3.27 6.15]


* 当设置decimals=2时，报错只支持decimals为0，不太合理。jax与torch均能配置。
* ms与jax不返回类型。

In [18]:
input = np.array([10.5, 21.5, 12.5, 31.5])

y1 = ms.ops.round(ms.tensor(input))
y2 = torch.round(torch.tensor(input))
y3 = jnp.round(input)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [10. 22. 12. 32.]


torch output:
 tensor([10., 22., 12., 32.], dtype=torch.float64)


jax output:
 [10. 22. 12. 32.]


面对0.5的情况，三种框架表现一致。

3、报错信息比较

In [14]:
y1 = ms.ops.round(input)

TypeError: Failed calling Round with "Round()(input=<class 'numpy.ndarray'>, decimals=int)".
The valid calling should be: 
"Round()(input=<Tensor>, decimals=<Tensor, int>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [15]:
y2 = torch.round(input)

TypeError: round(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [6]:
input = [2, 4, 3, 1]
y3 = jnp.round(input)

TypeError: round requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。