## mindspore.ops.tile(input, dims) -〉 Tensor
根据指定维度复制input。
- 输入：
    * input：mindspore的tensor。
    * dims：tuple[int]。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | a           |
| dims        | dims        | reps        |

2、返回值比较

In [3]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([[1, 2],
                  [3, 4,]])

y1 = ms.ops.tile(ms.tensor(input), (2, 3))
y2 = torch.tile(torch.tensor(input), (2, 3))
y3 = jnp.tile(input, (2, 3))
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


torch output:
 tensor([[1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4],
        [1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4]])


jax output:
 [[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


* ms与jax不返回类型。

3、报错信息比较

In [4]:
y1 = ms.ops.tile(input, (2, 3))

TypeError: Failed calling Tile with "Tile()(input=<class 'numpy.ndarray'>, dims=Tuple<int, int>)".
The valid calling should be: 
"Tile()(input=<Tensor>, dims=<Tensor, tuple of int>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [5]:
y2 = torch.tile(input, (2, 3))

TypeError: tile(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [6]:
input = [2, 4, 3, 1]
y3 = jnp.tile(input, (2, 3))

TypeError: tile requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。