## mindspore.ops.where(condition, input, other) -〉 Tensor
根据条件从输入中选择元素组成返回tensor。
- 输入：
    * condition：Tensor[bool]。
    * input：Tensor, Scalar。
    * other：Tensor, Scalar。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| condition   | condition   | condition   |
| input       | input       | x           |
| other       | other       | y           |
|             | out         | size        |
|             |             | fill_value  |

* torch额外提供了out出参方式。
* jax提供了size和fill_value用于处理当x和y为空的情况。ms与torch的input和other均为必选参数。

2、返回值比较

In [3]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([[-0.4620,  0.3139],
                  [ 0.3898, -0.7197],
                  [ 0.0478, -0.1657]])

y1 = ms.ops.where(ms.tensor(input) > 0, ms.tensor(input), 0)
y2 = torch.where(torch.tensor(input) > 0, torch.tensor(input), 0)
y3 = jnp.where(input > 0, input, 0)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[0.     0.3139]
 [0.3898 0.    ]
 [0.0478 0.    ]]


torch output:
 tensor([[0.0000, 0.3139],
        [0.3898, 0.0000],
        [0.0478, 0.0000]], dtype=torch.float64)


jax output:
 [[0.     0.3139]
 [0.3898 0.    ]
 [0.0478 0.    ]]


* ms与jax不返回类型。

3、报错信息比较

In [7]:
y1 = ms.ops.where(input > 0, input, 0)

TypeError: Failed calling Select with "Select()(condition=<class 'numpy.ndarray'>, input=<class 'numpy.ndarray'>, other=int)".
The valid calling should be: 
"Select()(condition=<Tensor>, input=<Number, Tensor>, other=<Number, Tensor>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [8]:
y2 = torch.where(input > 0, input, 0)

TypeError: where() received an invalid combination of arguments - got (numpy.ndarray, numpy.ndarray, int), but expected one of:
 * (Tensor condition)
 * (Tensor condition, Tensor input, Tensor other, *, Tensor out)
 * (Tensor condition, Number self, Tensor other)
      didn't match because some of the arguments have invalid types: (!numpy.ndarray!, !numpy.ndarray!, !int!)
 * (Tensor condition, Tensor input, Number other)
      didn't match because some of the arguments have invalid types: (!numpy.ndarray!, !numpy.ndarray!, !int!)
 * (Tensor condition, Number self, Number other)
      didn't match because some of the arguments have invalid types: (!numpy.ndarray!, !numpy.ndarray!, !int!)


In [9]:
input = [2, 4, 3, 1]
y3 = jnp.where(input > 0, input, 0)

TypeError: '>' not supported between instances of 'list' and 'int'

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。