## mindspore.ops.reciprocal(input) -〉 Tensor
返回输入的每个元素的倒数。
- 输入：input必须为mindspore的tensor。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | x           |
|             | out         |             |

* torch额外提供了out出参方式

2、返回值比较

In [1]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([1.0, 2.0, 4.0])

y1 = ms.ops.reciprocal(ms.tensor(input))
y2 = torch.reciprocal(torch.tensor(input))
y3 = jnp.reciprocal(input)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [1.   0.5  0.25]


torch output:
 tensor([1.0000, 0.5000, 0.2500], dtype=torch.float64)


jax output:
 [1.   0.5  0.25]


* ms与jax不返回类型。

3、报错信息比较

In [2]:
y1 = ms.ops.reciprocal(input)

TypeError: Failed calling Reciprocal with "Reciprocal()(x=<class 'numpy.ndarray'>)".
The valid calling should be: 
"Reciprocal()(x=<Tensor>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [3]:
y2 = torch.reciprocal(input)

TypeError: reciprocal(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [4]:
input = [2, 4, 3, 1]
y3 = jnp.reciprocal(input)

TypeError: reciprocal requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。