## mindspore.ops.ones(size, dtype=None) -〉 Tensor
创建一个值全为0的Tensor。
- 输入：
    * size: tuple[int]]、list[int]、int或mindspore的tensor（数据类型为int32或int64）。
    * dtype: mindspore.dtype。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| size        | size        | shape       |
| dtype       | out         | dtype       |
|             | dtype       | device      |
|             | layout      |       |
|             | device      |          |
|             | requires_grad   |        |


* torch额外提供了out出参方式, layout用于设置内存存储结构，以及requires_grad设置自动求导是否记录操作。
* torch和jax都提供了device参数，用于设置返回值提交到哪个设备上。
* mindspore.ops.ones与mindspore.ops.zeros参数名不一致。

2、返回值比较

In [1]:
import mindspore as ms
import torch
import jax.numpy as jnp

y1 = ms.ops.zeros((2,3))
y2 = torch.zeros((2,3))
y3 = jnp.zeros((2,3))
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[0. 0. 0.]
 [0. 0. 0.]]


torch output:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


jax output:
 [[0. 0. 0.]
 [0. 0. 0.]]


指定数据类型：

In [2]:
y1 = ms.ops.zeros(4, dtype=ms.bool_)
y2 = torch.zeros(4, dtype=bool)
y3 = jnp.zeros(4, dtype=bool)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [False False False False]


torch output:
 tensor([False, False, False, False])


jax output:
 [False False False False]


* ms与jax不返回类型。

3、报错信息比较：

In [3]:
y1 = ms.ops.zeros(1.5)

TypeError: Failed calling Zeros with "Zeros()(size=float, dtype=mindspore.dtype)".
The valid calling should be: 
"Zeros()(size=<int, list of int, Tensor, tuple of int>, dtype=<mindspore.dtype>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [4]:
y2 = torch.zeros(1.5)

TypeError: zeros(): argument 'size' (position 1) must be tuple of ints, but found element of type float at pos 0

In [5]:
y3 = jnp.zeros(1.5)

TypeError: Shapes must be 1D sequences of concrete values of integer type, got (1.5,).

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。