## mindspore.ops.transpose(input, input_perm) -〉 Tensor
按指定的排列对输入进行数据重排。
- 输入：
    * input：mindspore的tensor。
    * input_perm：tuple(int)。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | a           |
| input_perm  | dim0        | axes        |
|             | dim1        |             |

* ms与jax相同，使用第二个参数来设置按什么维度顺序进行重排。torch使用第二、三个参数设置按哪个维度进行重排。

2、返回值比较

未设定重排维度情况下，默认值比较：

In [12]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([[[1, 2, 3], 
                   [4, 5, 6]], 
                   [[7, 8, 9], 
                   [10, 11, 12]]])

# y1 = ms.ops.transpose(ms.tensor(input))
# y2 = torch.transpose(torch.tensor(input))
y3 = jnp.transpose(input)
# print ('mindspore output:\n',y1)
# print('\n')
# print ('torch output:\n',y2)
# print('\n')
print ('jax output:\n',y3)

jax output:
 [[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


* ms与torch的input_perm、dim0和dim1均为必选参数必须设置。
* jax的默认行为是按将整个维度倒序排列，如上述例子，等同于设置axes=(2, 1, 0)

In [11]:
y1 = ms.ops.transpose(ms.tensor(input), (0, 2, 1))
y2 = torch.transpose(torch.tensor(input), dim0=2, dim1=1)
y3 = jnp.transpose(input, (0, 2, 1))
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]


torch output:
 tensor([[[ 1,  4],
         [ 2,  5],
         [ 3,  6]],

        [[ 7, 10],
         [ 8, 11],
         [ 9, 12]]])


jax output:
 [[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]


* ms与jax不返回类型。

3、报错信息比较

In [13]:
y1 = ms.ops.transpose(input, (0, 2, 1))

TypeError: Failed calling Transpose with "Transpose()(input=<class 'numpy.ndarray'>, input_perm=Tuple<int, int, int>)".
The valid calling should be: 
"Transpose()(input=<Tensor>, input_perm=<tuple of int>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [14]:
y2 = torch.transpose(input, (0, 2, 1))

TypeError: transpose() received an invalid combination of arguments - got (numpy.ndarray, tuple), but expected one of:
 * (Tensor input, int dim0, int dim1)
 * (Tensor input, name dim0, name dim1)


In [15]:
input = [2, 4, 3, 1]
y3 = jnp.transpose(input, (0, 2, 1))

TypeError: transpose requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。