## mindspore.ops.tensor_dot(x1, x2, axes) -〉 Tensor
在指定轴上对两个输入进行点乘操作。
- 输入：
    * x1：mindspore的tensor, 数据类型为float16或float32。
    * x2：mindspore的tensor, 数据类型为float16或float32。
    * axes：int, tuple(int), tuple(tuple(int)), list(list(int))。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| x1          | a           | a           |
| x2          | b           | b           |
| axes        | dims        | axes        |
|             | out         | precision   |
|             |             | preferred_element_type |
* torch额外提供了out出参
* jax额外提供了precision用于设置后端精度，以及preferred_element_type设置返回值的数据类型。

2、返回值比较

In [3]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

x1 = np.arange(24.).reshape(2, 3, 4)
x2 = np.ones((3, 4, 5))

y1 = ms.ops.tensor_dot(ms.tensor(x1), ms.tensor(x2), axes=([1, 2], [0, 1]))
y2 = torch.tensordot(torch.tensor(x1), torch.tensor(x2), dims=([1, 2], [0, 1]))
y3 = jnp.tensordot(x1, x2, axes=([1, 2], [0, 1]))
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[ 66.  66.  66.  66.  66.]
 [210. 210. 210. 210. 210.]]


torch output:
 tensor([[ 66.,  66.,  66.,  66.,  66.],
        [210., 210., 210., 210., 210.]], dtype=torch.float64)


jax output:
 [[ 66.  66.  66.  66.  66.]
 [210. 210. 210. 210. 210.]]


* ms与jax不返回类型。

3、报错信息比较

In [4]:
y1 = ms.ops.tensor_dot(x1, x2, axes=([1, 2], [0, 1]))

TypeError: For primitive[Shape], the input argument must be Tensor, but got <class 'numpy.ndarray'>.

In [5]:
y2 = torch.tensordot(x1, x2, dims=([1, 2], [0, 1]))

TypeError: tensordot(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [6]:
input = [2, 4, 3, 1]
y3 = jnp.tensordot(input, x2, axes=([1, 2], [0, 1]))

TypeError: tensordot requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。