## mindspore.ops.tril(input, diagonal=0) -〉 Tensor
返回输入的对角线和下面的元素，并将其他元素设置为0。
- 输入：
    * input：mindspore的tensor。
    * diagonal：int。
- 返回：mindspore的tensor。

1、参数比较：
| mindspore   | torch       | jax         |
| :----:      | :----:      | :----:      |
| input       | input       | m           |
| diagonal    | diagonal    | k           |
|             | out         |             |

* torch额外提供了out出参。

2、返回值比较

二维输入下diagonal默认值比较：

In [4]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

y1 = ms.ops.tril(ms.tensor(input))
y2 = torch.tril(torch.tensor(input))
y3 = jnp.tril(input)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[ 1  0  0  0]
 [ 5  6  0  0]
 [ 9 10 11  0]]


torch output:
 tensor([[ 1,  0,  0,  0],
        [ 5,  6,  0,  0],
        [ 9, 10, 11,  0]])


jax output:
 [[ 1  0  0  0]
 [ 5  6  0  0]
 [ 9 10 11  0]]


In [5]:
y1 = ms.ops.tril(ms.tensor(input), 1)
y2 = torch.tril(torch.tensor(input), 1)
y3 = jnp.tril(input, 1)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[ 1  2  0  0]
 [ 5  6  7  0]
 [ 9 10 11 12]]


torch output:
 tensor([[ 1,  2,  0,  0],
        [ 5,  6,  7,  0],
        [ 9, 10, 11, 12]])


jax output:
 [[ 1  2  0  0]
 [ 5  6  7  0]
 [ 9 10 11 12]]


三维输入：

In [6]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([[[1, 2],
                  [3, 4]],
                 [[5, 6],
                  [7, 8]]])

y1 = ms.ops.tril(ms.tensor(input))
y2 = torch.tril(torch.tensor(input))
y3 = jnp.tril(input)
print ('mindspore output:\n',y1)
print('\n')
print ('torch output:\n',y2)
print('\n')
print ('jax output:\n',y3)

mindspore output:
 [[[1 0]
  [3 4]]

 [[5 0]
  [7 8]]]


torch output:
 tensor([[[1, 0],
         [3, 4]],

        [[5, 0],
         [7, 8]]])


jax output:
 [[[1 0]
  [3 4]]

 [[5 0]
  [7 8]]]


* ms与jax不返回类型。

3、报错信息比较

In [7]:
y1 = ms.ops.tril(input)

TypeError: For Primitive[Tril], the type of input argument[x] must be Tensor but got External.

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/core/utils/check_convert_utils.cc:880 CheckTensorTypeValid


In [8]:
y2 = torch.tril(input)

TypeError: tril(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [9]:
input = [2, 4, 3, 1]
y3 = jnp.tril(input)

TypeError: tril requires ndarray or scalar arguments, got <class 'list'> at position 0.

当输入类型不正确时，报错信息torch简洁明确。建议ms优化。